# Generated by Django 5.2.6 on 2025-10-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0002_categoriearticle_categorielivre_bienetablissement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienetablissement',
            name='type_bien',
            field=models.CharField(choices=[('SALLE_CLASSE', 'Salle de classe'), ('BUREAU', 'Bureau'), ('LABORATOIRE', 'Laboratoire'), ('BIBLIOTHEQUE', 'Bibliothèque'), ('TOILETTE', 'Toilette'), ('CANTINE', 'Cantine'), ('TERRAIN_SPORT', 'Terrain de sport'), ('COUR', 'Cour'), ('PARKING', 'Parking'), ('TABLE', 'Table(s)'), ('CHAISE', 'Chaise(s)'), ('ARMOIRE', 'Armoire'), ('ETAGERE', 'Étagère'), ('CLIMATISEUR', 'Climatiseur'), ('ORDINATEUR', 'Ordinateur'), ('IMPRIMANTE', 'Imprimante'), ('PROJECTEUR', 'Projecteur'), ('TABLEAU', 'Tableau'), ('GLOBE_TERRESTRE', 'Globe terrestre'), ('CARTE', 'Carte géographique'), ('COMPAS', 'Compas'), ('EQUERRE', 'Équerre'), ('AMPOULE', 'Ampoule(s)'), ('VENTILATEUR', 'Ventilateur'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de bien'),
        ),
    ]
