# Generated by Django 5.2.6 on 2026-03-05 22:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0003_alter_bienetablissement_type_bien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Montant TTC (GNF)'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Montant TVA (GNF)'),
        ),
    ]
