# Generated by Django 5.2.6 on 2026-08-02 08:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def rattacher_anciens_biens(apps, schema_editor):
    BienEtablissement = apps.get_model('depenses', 'BienEtablissement')
    Profil = apps.get_model('utilisateurs', 'Profil')
    ecoles_par_utilisateur = dict(
        Profil.objects.exclude(ecole_id=None).values_list('user_id', 'ecole_id')
    )
    for bien in BienEtablissement.objects.all().iterator():
        champs = []
        if not bien.ecole_id and bien.cree_par_id in ecoles_par_utilisateur:
            bien.ecole_id = ecoles_par_utilisateur[bien.cree_par_id]
            champs.append('ecole')
        if bien.quantite_achetee == 0:
            bien.quantite_achetee = 1
            champs.append('quantite_achetee')
        if bien.prix_achat_unitaire == 0 and bien.valeur_acquisition:
            bien.prix_achat_unitaire = bien.valeur_acquisition
            champs.append('prix_achat_unitaire')
        if champs:
            bien.save(update_fields=champs)


def migration_inverse_vide(apps, schema_editor):
    # Les valeurs enrichies restent en place si la migration est annulée.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0007_logistique_bibliotheque_sync_tracking'),
        ('eleves', '0016_ecole_bonus_suivi_actif'),
        ('utilisateurs', '0014_profil_lecture_seule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bienetablissement',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biens_etablissement', to='eleves.ecole', verbose_name='École'),
        ),
        migrations.AddField(
            model_name='bienetablissement',
            name='marque',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='bienetablissement',
            name='prix_achat_unitaire',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15, verbose_name="Prix d'achat unitaire (GNF)"),
        ),
        migrations.AddField(
            model_name='bienetablissement',
            name='quantite_achetee',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité achetée'),
        ),
        migrations.AddField(
            model_name='bienetablissement',
            name='quantite_gatee',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité gâtée / hors service'),
        ),
        migrations.AddField(
            model_name='bienetablissement',
            name='quantite_utilisee',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité utilisée / affectée'),
        ),
        migrations.AlterField(
            model_name='bienetablissement',
            name='localisation',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='bienetablissement',
            name='type_bien',
            field=models.CharField(choices=[('SALLE_CLASSE', 'Salle de classe'), ('BUREAU', 'Bureau'), ('LABORATOIRE', 'Laboratoire'), ('BIBLIOTHEQUE', 'Bibliothèque'), ('TOILETTE', 'Toilette'), ('CANTINE', 'Cantine'), ('TERRAIN_SPORT', 'Terrain de sport'), ('COUR', 'Cour'), ('PARKING', 'Parking'), ('TABLE', 'Table(s)'), ('CHAISE', 'Chaise(s)'), ('ARMOIRE', 'Armoire'), ('ETAGERE', 'Étagère'), ('FOURNITURE', 'Fourniture'), ('MARQUEUR', 'Marqueur(s)'), ('CLIMATISEUR', 'Climatiseur'), ('ORDINATEUR', 'Ordinateur'), ('IMPRIMANTE', 'Imprimante'), ('PROJECTEUR', 'Projecteur'), ('TABLEAU', 'Tableau'), ('GLOBE_TERRESTRE', 'Globe terrestre'), ('CARTE', 'Carte géographique'), ('COMPAS', 'Compas'), ('EQUERRE', 'Équerre'), ('AMPOULE', 'Ampoule(s)'), ('VENTILATEUR', 'Ventilateur'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de bien'),
        ),
        migrations.RunPython(rattacher_anciens_biens, migration_inverse_vide),
        migrations.AddConstraint(
            model_name='bienetablissement',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('quantite_utilisee__lte', models.F('quantite_achetee') - models.F('quantite_gatee'))
                ),
                name='bien_quantites_coherentes',
            ),
        ),
        migrations.CreateModel(
            name='ContributionPapierRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('annee_scolaire', models.CharField(max_length=9, verbose_name='Année scolaire')),
                ('mode_contribution', models.CharField(choices=[('PAPIER', 'Papier RAM remis'), ('ARGENT', 'Montant payé à la place')], max_length=10, verbose_name='Mode')),
                ('nombre_paquets', models.PositiveIntegerField(default=0, verbose_name='Nombre de paquets')),
                ('montant_paye', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15, verbose_name='Montant payé (GNF)')),
                ('date_contribution', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_papier_ram_creees', to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions_papier_ram', to='eleves.ecole')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions_papier_ram', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Contribution papier RAM',
                'verbose_name_plural': 'Contributions papier RAM',
                'ordering': ['-date_contribution', 'eleve__nom', 'eleve__prenom'],
                'constraints': [
                    models.UniqueConstraint(fields=('ecole', 'eleve', 'annee_scolaire'), name='unique_papier_ram_eleve_annee'),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(('mode_contribution', 'PAPIER'), ('montant_paye', 0), ('nombre_paquets__gte', 1)),
                            models.Q(('mode_contribution', 'ARGENT'), ('montant_paye__gt', 0), ('nombre_paquets', 0)),
                            _connector='OR',
                        ),
                        name='papier_ram_mode_coherent',
                    ),
                ],
            },
        ),
    ]
