# Generated by Django 5.2.6 on 2026-08-03 02:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0008_bienetablissement_ecole_bienetablissement_marque_and_more'),
        ('eleves', '0016_ecole_bonus_suivi_actif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitFourniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('code_produit', models.CharField(blank=True, max_length=50, verbose_name='Code produit')),
                ('nom', models.CharField(max_length=200, verbose_name='Produit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('quantite_stock', models.PositiveIntegerField(default=0, verbose_name='Quantité mise en stock')),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15, verbose_name="Prix d'achat unitaire (GNF)")),
                ('prix_vente_unitaire', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15, verbose_name='Prix de vente unitaire (GNF)')),
                ('seuil_alerte', models.PositiveIntegerField(default=5, verbose_name="Seuil d'alerte")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_fournitures_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_fournitures', to='eleves.ecole', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Produit de fourniture scolaire',
                'verbose_name_plural': 'Produits de fournitures scolaires',
                'ordering': ['nom', 'code_produit'],
            },
        ),
        migrations.CreateModel(
            name='VenteFourniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Référence')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité vendue')),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15, verbose_name="Prix d'achat unitaire (GNF)")),
                ('prix_vente_unitaire', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Prix de vente unitaire (GNF)')),
                ('date_vente', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de vente')),
                ('acheteur', models.CharField(blank=True, max_length=200, verbose_name='Acheteur')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_fournitures_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='depenses.produitfourniture', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Vente de fourniture scolaire',
                'verbose_name_plural': 'Ventes de fournitures scolaires',
                'ordering': ['-date_vente', '-date_creation'],
            },
        ),
        migrations.AddConstraint(
            model_name='produitfourniture',
            constraint=models.UniqueConstraint(fields=('ecole', 'code_produit'), name='unique_produit_fourniture_ecole_code'),
        ),
        migrations.AddConstraint(
            model_name='produitfourniture',
            constraint=models.CheckConstraint(condition=models.Q(('prix_achat_unitaire__gte', 0)), name='produit_fourniture_prix_achat_positif'),
        ),
        migrations.AddConstraint(
            model_name='produitfourniture',
            constraint=models.CheckConstraint(condition=models.Q(('prix_vente_unitaire__gte', 0)), name='produit_fourniture_prix_vente_positif'),
        ),
        migrations.AddConstraint(
            model_name='ventefourniture',
            constraint=models.CheckConstraint(condition=models.Q(('quantite__gte', 1)), name='vente_fourniture_quantite_positive'),
        ),
        migrations.AddConstraint(
            model_name='ventefourniture',
            constraint=models.CheckConstraint(condition=models.Q(('prix_achat_unitaire__gte', 0)), name='vente_fourniture_prix_achat_positif'),
        ),
        migrations.AddConstraint(
            model_name='ventefourniture',
            constraint=models.CheckConstraint(condition=models.Q(('prix_vente_unitaire__gt', 0)), name='vente_fourniture_prix_vente_positif'),
        ),
    ]
