# Generated by Django 5.2.6 on 2026-08-05 05:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0009_produitfourniture_ventefourniture_and_more'),
        ('eleves', '0016_ecole_bonus_suivi_actif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnementInformatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, editable=False, verbose_name='Date')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (GNF)')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_debut', models.DateField(verbose_name="Début de l'abonnement")),
                ('date_fin', models.DateField(verbose_name="Fin de l'abonnement")),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='eleves.ecole', verbose_name='École')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_informatique', to='eleves.eleve', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Abonnement informatique',
                'verbose_name_plural': 'Abonnements informatique',
                'ordering': ['-date_fin', '-id'],
                'abstract': False,
                'indexes': [models.Index(fields=['ecole', '-date_fin'], name='depenses_ab_ecole_i_bbab83_idx'), models.Index(fields=['eleve', '-date_fin'], name='depenses_ab_eleve_i_afc74e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DepenseCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, editable=False, verbose_name='Date')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (GNF)')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='eleves.ecole', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Dépense de cuisine',
                'verbose_name_plural': 'Dépenses de cuisine',
                'ordering': ['-date', '-id'],
                'abstract': False,
                'indexes': [models.Index(fields=['ecole', '-date'], name='depenses_de_ecole_i_1da03c_idx')],
            },
        ),
        migrations.CreateModel(
            name='DepenseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, editable=False, verbose_name='Date')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (GNF)')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='eleves.ecole', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Dépense de document',
                'verbose_name_plural': 'Dépenses de documents',
                'ordering': ['-date', '-id'],
                'abstract': False,
                'indexes': [models.Index(fields=['ecole', '-date'], name='depenses_de_ecole_i_e67a36_idx')],
            },
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, editable=False, verbose_name='Date')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (GNF)')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('lieu_versement', models.CharField(max_length=200, verbose_name='Lieu de versement')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='eleves.ecole', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Versement',
                'verbose_name_plural': 'Versements',
                'ordering': ['-date', '-id'],
                'abstract': False,
                'indexes': [models.Index(fields=['ecole', '-date'], name='depenses_ve_ecole_i_59c8d1_idx')],
            },
        ),
    ]
