# Generated by Django 5.2.6 on 2026-08-12 13:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0010_abonnementinformatique_depensecuisine_and_more'),
        ('eleves', '0019_elevecorbeille_eleve_est_dans_corbeille_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, editable=False, verbose_name='Date')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (GNF)')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=200, verbose_name='Provenance')),
                ('type_entree', models.CharField(choices=[('SCOLARITE', 'Scolarité'), ('INSCRIPTION', 'Inscription'), ('CANTINE', 'Cantine'), ('TRANSPORT', 'Transport'), ('FOURNITURE', 'Fournitures scolaires'), ('INFORMATIQUE', 'Informatique'), ('DON', 'Don'), ('SUBVENTION', 'Subvention'), ('LOCATION', 'Location'), ('AUTRE', 'Autre entrée')], default='AUTRE', max_length=20, verbose_name="Type d'entrée")),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement bancaire'), ('AUTRE', 'Autre')], default='ESPECES', max_length=20, verbose_name="Mode d'encaissement")),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='Référence / N° de reçu')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='eleves.ecole', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Entrée',
                'verbose_name_plural': 'Entrées',
                'ordering': ['-date', '-id'],
                'abstract': False,
                'indexes': [models.Index(fields=['ecole', '-date'], name='depenses_en_ecole_i_747d6a_idx'), models.Index(fields=['ecole', 'type_entree'], name='depenses_en_ecole_i_43f931_idx')],
            },
        ),
    ]
