# Generated by Django 5.2.6 on 2026-08-14 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0011_entree'),
        ('eleves', '0019_elevecorbeille_eleve_est_dans_corbeille_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembrePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('fonction', models.CharField(max_length=120, verbose_name='Fonction')),
                ('groupe', models.CharField(choices=[('MATERNELLE_PRIMAIRE', 'Maternelle et primaire'), ('COLLEGE', 'Collège'), ('DIRECTION', 'Équipe de direction')], default='MATERNELLE_PRIMAIRE', max_length=25, verbose_name='Groupe')),
                ('actif', models.BooleanField(default=True, verbose_name='En activité')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres_personnel', to='eleves.ecole', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Membre du personnel',
                'verbose_name_plural': 'Membres du personnel',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='SalaireMensuelPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('mois', models.PositiveSmallIntegerField(verbose_name='Mois')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (GNF)')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaires_mensuels', to='depenses.membrepersonnel', verbose_name='Membre du personnel')),
            ],
            options={
                'verbose_name': 'Salaire mensuel du personnel',
                'verbose_name_plural': 'Salaires mensuels du personnel',
                'ordering': ['-annee', '-mois'],
            },
        ),
        migrations.AddIndex(
            model_name='membrepersonnel',
            index=models.Index(fields=['ecole', 'groupe'], name='depenses_me_ecole_i_0f2052_idx'),
        ),
        migrations.AddIndex(
            model_name='salairemensuelpersonnel',
            index=models.Index(fields=['annee', 'mois'], name='depenses_sa_annee_5789a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='salairemensuelpersonnel',
            constraint=models.UniqueConstraint(fields=('membre', 'annee', 'mois'), name='salaire_personnel_unique_mois'),
        ),
    ]
