# Generated by Django 5.2.5 on 2025-09-19 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0003_classe_code_matricule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecoles_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ecole',
            name='etat',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validée'), ('REJETE', 'Rejetée')], db_index=True, default='EN_ATTENTE', max_length=20),
        ),
    ]
