# Generated by Cascade on 2025-09-20
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0004_ecole_created_by_ecole_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='ire',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IRE'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='dpe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DPE'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='desee',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DESEE'),
        ),
    ]
