# Generated by Cascade on 2025-09-20
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0005_ecole_official_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='grilletarifaire',
            name='frais_reinscription',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Frais de réinscription (GNF)'),
        ),
    ]
