# Generated by Django 5.2.5 on 2025-09-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0006_grilletarifaire_frais_reinscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='grilletarifaire',
            name='date_echeance_inscription_defaut',
            field=models.DateField(blank=True, null=True, verbose_name='Échéance inscription (défaut)'),
        ),
        migrations.AddField(
            model_name='grilletarifaire',
            name='date_echeance_tranche_1_defaut',
            field=models.DateField(blank=True, null=True, verbose_name='Échéance Tranche 1 (défaut)'),
        ),
        migrations.AddField(
            model_name='grilletarifaire',
            name='date_echeance_tranche_2_defaut',
            field=models.DateField(blank=True, null=True, verbose_name='Échéance Tranche 2 (défaut)'),
        ),
        migrations.AddField(
            model_name='grilletarifaire',
            name='date_echeance_tranche_3_defaut',
            field=models.DateField(blank=True, null=True, verbose_name='Échéance Tranche 3 (défaut)'),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='etat',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validée'), ('REJETE', 'Rejetée')], db_index=True, default='BROUILLON', max_length=20),
        ),
    ]
