# Generated by Django 5.2.5 on 2025-09-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0007_grilletarifaire_date_echeance_inscription_defaut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='code_prefixe',
            field=models.CharField(blank=True, help_text="Préfixe d'école pour les matricules, ex: AL-FUR/ (laisser vide pour ne pas utiliser)", max_length=20, null=True, verbose_name='Préfixe matricules'),
        ),
    ]
