# Generated by Django 5.2.7 on 2025-10-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0008_ecole_code_prefixe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
    ]
