# Generated by Django 5.2.7 on 2025-12-17 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0009_alter_eleve_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='date_inscription',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'inscription"),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='responsable_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves_principal', to='eleves.responsable', verbose_name='Responsable principal'),
        ),
    ]
