# Generated by Django 5.2.6 on 2026-03-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0011_ecole_telephone2_telephone3'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='censeur',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Censeur de l'établissement"),
        ),
    ]
