# Generated by Django 5.2.6 on 2026-03-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0012_ecole_censeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='image',
            field=models.ImageField(blank=True, help_text="Photo du batiment de l'ecole (affichee sur le livret scolaire)", null=True, upload_to='ecoles/images/', verbose_name="Photo de l'ecole"),
        ),
        migrations.AlterField(
            model_name='historiqueeleve',
            name='action',
            field=models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('CHANGEMENT_CLASSE', 'Changement de classe'), ('CHANGEMENT_STATUT', 'Changement de statut'), ('SUSPENSION', 'Suspension'), ('EXCLUSION', 'Exclusion'), ('TRANSFERT', 'Transfert'), ('DIPLOME', 'Diplômé / Archivé'), ('FIN_CYCLE', 'Fin de cycle')], max_length=20, verbose_name='Action'),
        ),
    ]
