# Generated by Django 5.2.6 on 2026-07-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0015_historiqueeleve_sync_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='bonus_suivi_actif',
            field=models.BooleanField(default=False, help_text='Si activé, les notes de suivi (cours, oral, écrit, devoirs, participation) ajoutent un bonus plafonné à la note mensuelle.', verbose_name='Activer le bonus de suivi'),
        ),
    ]
