# Generated by Django 5.2.6 on 2026-08-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0016_ecole_bonus_suivi_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='garde_prolongee',
            field=models.BooleanField(default=False, help_text="L'élève reste à l'école au-delà des heures de cours, le temps que les parents viennent le récupérer en sortant du travail. Applique le tarif forfaitaire annuel correspondant (maternelle/garderie ou primaire).", verbose_name='Garde prolongée (au-delà des heures de cours)'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.CharField(choices=[('GARDERIE', 'Garderie'), ('CRECHE', 'Crèche'), ('TOUTE_PETITE_SECTION', 'Toute petite section'), ('PETITE_SECTION', 'Petite section'), ('MOYENNE_SECTION', 'Moyenne section'), ('GRANDE_SECTION', 'Grande section'), ('MATERNELLE', 'Maternelle'), ('PRIMAIRE_1', 'Primaire 1ère'), ('PRIMAIRE_2', 'Primaire 2ème'), ('PRIMAIRE_3', 'Primaire 3ème'), ('PRIMAIRE_4', 'Primaire 4ème'), ('PRIMAIRE_5', 'Primaire 5ème'), ('PRIMAIRE_6', 'Primaire 6ème'), ('COLLEGE_7', 'Collège 7ème'), ('COLLEGE_8', 'Collège 8ème'), ('COLLEGE_9', 'Collège 9ème'), ('COLLEGE_10', 'Collège 10ème'), ('LYCEE_11', 'Lycée 11ème'), ('LYCEE_12', 'Lycée 12ème'), ('TERMINALE', 'Terminale')], max_length=20, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='grilletarifaire',
            name='niveau',
            field=models.CharField(choices=[('GARDERIE', 'Garderie'), ('CRECHE', 'Crèche'), ('TOUTE_PETITE_SECTION', 'Toute petite section'), ('PETITE_SECTION', 'Petite section'), ('MOYENNE_SECTION', 'Moyenne section'), ('GRANDE_SECTION', 'Grande section'), ('MATERNELLE', 'Maternelle'), ('PRIMAIRE_1', 'Primaire 1ère'), ('PRIMAIRE_2', 'Primaire 2ème'), ('PRIMAIRE_3', 'Primaire 3ème'), ('PRIMAIRE_4', 'Primaire 4ème'), ('PRIMAIRE_5', 'Primaire 5ème'), ('PRIMAIRE_6', 'Primaire 6ème'), ('COLLEGE_7', 'Collège 7ème'), ('COLLEGE_8', 'Collège 8ème'), ('COLLEGE_9', 'Collège 9ème'), ('COLLEGE_10', 'Collège 10ème'), ('LYCEE_11', 'Lycée 11ème'), ('LYCEE_12', 'Lycée 12ème'), ('TERMINALE', 'Terminale')], max_length=20, verbose_name='Niveau'),
        ),
    ]
