# Generated by Django 5.2.6 on 2026-08-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0017_eleve_garde_prolongee_alter_classe_niveau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='garde_prolongee',
            field=models.BooleanField(default=False, help_text="L'élève reste à l'école au-delà des heures de cours, le temps que les parents viennent le récupérer en sortant du travail. La scolarité annuelle passe alors au forfait de son cycle (2 700 000 GNF en maternelle et garderie, 2 800 000 au primaire, 2 850 000 en 10ème année), auquel s'ajoutent les frais d'inscription ou de réinscription.", verbose_name='Garde prolongée (au-delà des heures de cours)'),
        ),
    ]
