# Generated by Django 5.2.6 on 2026-08-09 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0018_alter_eleve_garde_prolongee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EleveCorbeille',
            fields=[
            ],
            options={
                'verbose_name': 'Élève dans la corbeille',
                'verbose_name_plural': 'Corbeille des élèves',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('eleves.eleve',),
        ),
        migrations.AddField(
            model_name='eleve',
            name='est_dans_corbeille',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Dans la corbeille'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='statut_avant_suppression',
            field=models.CharField(blank=True, choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('EXCLU', 'Exclu'), ('TRANSFERE', 'Transféré'), ('DIPLOME', 'Diplômé')], max_length=20, verbose_name='Statut avant suppression'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='supprime_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='supprime_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves_places_corbeille', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par'),
        ),
    ]
