# Generated by Django 5.2.6 on 2026-08-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0019_elevecorbeille_eleve_est_dans_corbeille_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='test_accueil_evalue',
            field=models.BooleanField(db_index=True, default=False, help_text="Cochez lorsque l'élève a passé et reçu l'évaluation du test d'accueil.", verbose_name="Test d'accueil évalué"),
        ),
    ]
