# Generated by Django 5.2.6 on 2026-09-01 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0020_eleve_test_accueil_evalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='couleur_accent',
            field=models.CharField(default='#F2B134', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Utilisez une couleur hexadécimale au format #RRGGBB.')], verbose_name="Couleur d'accent"),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_avertissement',
            field=models.CharField(default='#F59E0B', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Utilisez une couleur hexadécimale au format #RRGGBB.')], verbose_name='Couleur avertissement'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_bordure_documents',
            field=models.CharField(default='#AFC3D6', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Utilisez une couleur hexadécimale au format #RRGGBB.')], verbose_name='Bordures des documents'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_danger',
            field=models.CharField(default='#DC3545', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Utilisez une couleur hexadécimale au format #RRGGBB.')], verbose_name='Couleur danger / retard'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_fond_documents',
            field=models.CharField(default='#F5F8FB', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Utilisez une couleur hexadécimale au format #RRGGBB.')], verbose_name='Fond clair des documents'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_information',
            field=models.CharField(default='#0EA5E9', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Utilisez une couleur hexadécimale au format #RRGGBB.')], verbose_name='Couleur information'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_primaire',
            field=models.CharField(default='#163B65', help_text='Navigation, titres, cartes principales et en-têtes de documents.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Utilisez une couleur hexadécimale au format #RRGGBB.')], verbose_name='Couleur principale'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_secondaire',
            field=models.CharField(default='#2F75B5', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Utilisez une couleur hexadécimale au format #RRGGBB.')], verbose_name='Couleur secondaire'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_succes',
            field=models.CharField(default='#198754', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Utilisez une couleur hexadécimale au format #RRGGBB.')], verbose_name='Couleur succès'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_texte_documents',
            field=models.CharField(default='#172B3A', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Utilisez une couleur hexadécimale au format #RRGGBB.')], verbose_name='Texte principal des documents'),
        ),
    ]
