# Generated by Django 5.2.6 on 2025-09-18 06:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('message', models.TextField(default='Le système est en maintenance. Veuillez réessayer plus tard.', help_text='Message affiché aux utilisateurs')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_activated', to=settings.AUTH_USER_MODEL)),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Utilisateurs autorisés pendant la maintenance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mode maintenance',
                'verbose_name_plural': 'Mode maintenance',
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DELETE', 'Suppression'), ('RESET', 'Réinitialisation'), ('BACKUP', 'Sauvegarde'), ('RESTORE', 'Restauration'), ('LOGIN', 'Connexion admin'), ('ERROR', 'Erreur système')], db_index=True, max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log système',
                'verbose_name_plural': 'Logs système',
                'ordering': ['-timestamp'],
            },
        ),
    ]
