# Generated by Django 5.2.6 on 2025-09-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='action',
            field=models.CharField(choices=[('DELETE', 'Suppression'), ('SUPPRESSION_DEFINITIVE', 'Suppression définitive'), ('RESET', 'Réinitialisation'), ('BACKUP', 'Sauvegarde'), ('RESTORE', 'Restauration'), ('LOGIN', 'Connexion admin'), ('ERROR', 'Erreur système')], db_index=True, max_length=30),
        ),
    ]
