# Generated by Django 5.2.6 on 2026-08-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_systemlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Numero de version, par exemple 1.3.0', max_length=20, unique=True)),
                ('url_telechargement', models.URLField(help_text="Adresse HTTPS de l'installateur (.exe). Par exemple une publication GitHub.", max_length=500)),
                ('sha256', models.CharField(help_text='Empreinte SHA-256 du fichier. Sous Windows : certutil -hashfile installateur.exe SHA256', max_length=64)),
                ('taille_octets', models.BigIntegerField(blank=True, help_text='Taille attendue du fichier. Facultatif.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Ce que cette version apporte, en clair.')),
                ('obligatoire', models.BooleanField(default=False, help_text="Installer sans attendre l'accord de l'utilisateur.")),
                ('publiee', models.BooleanField(db_index=True, default=False, help_text='Tant que cette case est decochee, aucun poste ne voit cette version.')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Version de l'application",
                'verbose_name_plural': "Versions de l'application",
                'ordering': ['-date_creation'],
            },
        ),
    ]
