# Generated by Django 5.2.7 on 2025-11-12 09:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0009_alter_eleve_date_naissance'),
        ('paiements', '0004_twilioinboundmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_inscription', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='Montant inscription (GNF)')),
                ('montant_scolarite', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='Montant scolarité annuelle (GNF)')),
                ('nombre_tranches', models.PositiveIntegerField(default=3, verbose_name='Nombre de tranches')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_paiement', to='eleves.classe', verbose_name='Classe')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurations_paiement_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration de paiement',
                'verbose_name_plural': 'Configurations de paiement',
                'ordering': ['classe__nom'],
            },
        ),
    ]
