# Generated by Django 5.2.6 on 2026-03-05 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0012_ecole_censeur'),
        ('paiements', '0005_add_configuration_paiement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='echeancierpaiement',
            index=models.Index(fields=['annee_scolaire'], name='paiements_e_annee_s_aa73e4_idx'),
        ),
        migrations.AddIndex(
            model_name='echeancierpaiement',
            index=models.Index(fields=['statut'], name='paiements_e_statut_08067b_idx'),
        ),
        migrations.AddIndex(
            model_name='echeancierpaiement',
            index=models.Index(fields=['annee_scolaire', 'statut'], name='paiements_e_annee_s_756ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['numero_recu'], name='paiements_p_numero__bf3e83_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['date_paiement'], name='paiements_p_date_pa_cc74b5_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['date_creation'], name='paiements_p_date_cr_f72f24_idx'),
        ),
    ]
