# Generated by Django 5.2.6 on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0011_paiementremise_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementremise',
            name='tranches_concernees',
            field=models.CharField(blank=True, default='', help_text='Numéros de tranches séparés par une virgule, ex: 1,2', max_length=10, verbose_name='Tranches concernées'),
        ),
        migrations.AddField(
            model_name='paiementremise',
            name='base_calcul',
            field=models.CharField(blank=True, choices=[('TRANCHES_DUES', 'Montant des tranches sélectionnées'), ('PAIEMENT_ECHEANCE', "Paiement à l'échéance")], default='', max_length=20, verbose_name='Base de calcul retenue'),
        ),
    ]
