# Generated by Django 5.2.6 on 2026-08-09 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0012_paiementremise_tranches_base_calcul'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueModificationPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recu', models.CharField(db_index=True, max_length=20)),
                ('eleve', models.CharField(blank=True, max_length=250)),
                ('motif', models.TextField()),
                ('champs_modifies', models.JSONField(blank=True, default=list)),
                ('donnees_avant', models.JSONField(default=dict)),
                ('donnees_apres', models.JSONField(default=dict)),
                ('date_modification', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_modifications', to='paiements.paiement')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_paiements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de modification de paiement',
                'verbose_name_plural': 'Historique des modifications de paiements',
                'ordering': ['-date_modification', '-id'],
            },
        ),
    ]
