# Generated by Django 5.2.6 on 2026-08-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0015_categoriser_types_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementremise',
            name='deduite_du_paiement',
            field=models.BooleanField(default=False, verbose_name='Déduite du montant du reçu'),
        ),
    ]
