# Generated by Django 5.2.6 on 2026-08-30 07:27

import django.db.models.deletion
from django.db import migrations, models


def renseigner_ecole_historiques(apps, schema_editor):
    Historique = apps.get_model('paiements', 'HistoriqueModificationPaiement')
    for historique in Historique.objects.filter(
        ecole__isnull=True,
        paiement__isnull=False,
    ).select_related('paiement__eleve__classe').iterator():
        paiement = historique.paiement
        ecole_id = paiement.ecole_encaissement_id
        if not ecole_id:
            try:
                ecole_id = paiement.eleve.classe.ecole_id
            except Exception:
                ecole_id = None
        if ecole_id:
            Historique.objects.filter(pk=historique.pk).update(ecole_id=ecole_id)


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0020_eleve_test_accueil_evalue'),
        ('paiements', '0017_paiement_portee_historique'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquemodificationpaiement',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_paiements', to='eleves.ecole', verbose_name='École concernée'),
        ),
        migrations.RunPython(
            renseigner_ecole_historiques,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='historiquemodificationpaiement',
            name='operation',
            field=models.CharField(choices=[('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression douce')], db_index=True, default='MODIFICATION', max_length=20),
        ),
        migrations.AddField(
            model_name='paiement',
            name='motif_annulation',
            field=models.TextField(blank=True, help_text="Conservé et synchronisé lors d'une suppression douce.", verbose_name="Motif de l'annulation"),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('REMBOURSE', 'Remboursé'), ('ANNULE', 'Annulé (suppression douce)')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
    ]
