# Generated by Django 5.2.6 on 2025-09-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_merge_0002_add_granular_permissions_0002_profil_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name="Compte validé par l'administrateur"),
        ),
    ]
