# Generated by Django 5.2.5 on 2025-09-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_profil_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='allowed_menus',
            field=models.JSONField(blank=True, default=list, verbose_name='Menus autorisés'),
        ),
    ]
