# Generated by Django 5.2.5 on 2025-09-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_profil_allowed_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='peut_gerer_notes',
            field=models.BooleanField(default=True, verbose_name='Peut gérer les notes et matières'),
        ),
    ]
