# Generated by Django 5.2.7 on 2025-10-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_profil_peut_gerer_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='peut_supprimer_eleves_definitivement',
            field=models.BooleanField(default=False, verbose_name='Peut supprimer les élèves définitivement'),
        ),
    ]
