# Generated by Django 5.2.7 on 2025-10-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0007_profil_peut_supprimer_eleves_definitivement'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='peut_supprimer_abonnements',
            field=models.BooleanField(default=False, verbose_name='Peut supprimer les abonnements'),
        ),
    ]
