# Generated by Django 5.1.3 on 2026-02-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilisateurs", "0011_alter_profil_ecole"),
    ]

    operations = [
        migrations.AddField(
            model_name="profil",
            name="peut_importer_eleves",
            field=models.BooleanField(
                default=False, verbose_name="Peut importer des élèves"
            ),
        ),
        migrations.AlterField(
            model_name="profil",
            name="peut_gerer_notes",
            field=models.BooleanField(
                default=True,
                verbose_name="Peut gérer les notes et matières (DÉSACTIVÉ)",
            ),
        ),
    ]
