# Generated by Django 5.2.6 on 2026-07-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0013_licenceserveur'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='lecture_seule',
            field=models.BooleanField(default=False, help_text="Si activé, l'utilisateur peut se connecter et voir les listes, mais ne peut rien ajouter, modifier ni supprimer.", verbose_name='Lecture seule (consultation uniquement)'),
        ),
    ]
