# Generated by Django 5.1.3 on 2026-01-31 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eleves", "0010_rendre_champs_optionnels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClasseNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom de la classe"),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("GARDERIE", "Garderie"),
                            ("MATERNELLE", "Maternelle"),
                            ("PRIMAIRE_1", "Primaire 1ère"),
                            ("PRIMAIRE_2", "Primaire 2ème"),
                            ("PRIMAIRE_3", "Primaire 3ème"),
                            ("PRIMAIRE_4", "Primaire 4ème"),
                            ("PRIMAIRE_5", "Primaire 5ème"),
                            ("PRIMAIRE_6", "Primaire 6ème"),
                            ("COLLEGE_7", "Collège 7ème"),
                            ("COLLEGE_8", "Collège 8ème"),
                            ("COLLEGE_9", "Collège 9ème"),
                            ("COLLEGE_10", "Collège 10ème"),
                            ("LYCEE_11", "Lycée 11ème"),
                            ("LYCEE_12", "Lycée 12ème"),
                            ("TERMINALE", "Terminale"),
                        ],
                        max_length=20,
                        verbose_name="Niveau",
                    ),
                ),
                (
                    "niveau_enseignement",
                    models.CharField(
                        choices=[
                            ("MATERNELLE", "Maternelle"),
                            ("PRIMAIRE", "Primaire"),
                            ("SECONDAIRE", "Secondaire"),
                        ],
                        default="SECONDAIRE",
                        max_length=20,
                        verbose_name="Niveau d'enseignement",
                    ),
                ),
                (
                    "annee_scolaire",
                    models.CharField(
                        help_text="Format: 2024-2025",
                        max_length=9,
                        verbose_name="Année scolaire",
                    ),
                ),
                (
                    "effectif",
                    models.PositiveIntegerField(default=0, verbose_name="Effectif"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Active")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classes_notes_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ecole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes_notes",
                        to="eleves.ecole",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classe (Notes)",
                "verbose_name_plural": "Classes (Notes)",
                "ordering": ["niveau", "nom"],
                "unique_together": {("ecole", "nom", "annee_scolaire")},
            },
        ),
        migrations.CreateModel(
            name="EvaluationMaternelle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trimestre",
                    models.CharField(
                        choices=[
                            ("TRIMESTRE_1", "Trimestre 1"),
                            ("TRIMESTRE_2", "Trimestre 2"),
                            ("TRIMESTRE_3", "Trimestre 3"),
                        ],
                        max_length=20,
                        verbose_name="Trimestre",
                    ),
                ),
                (
                    "annee_scolaire",
                    models.CharField(max_length=9, verbose_name="Année scolaire"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations_maternelle",
                        to="notes.classenote",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations_maternelle_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations_maternelle",
                        to="eleves.eleve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation maternelle",
                "verbose_name_plural": "Évaluations maternelle",
                "ordering": ["eleve", "trimestre"],
                "unique_together": {("eleve", "classe", "trimestre", "annee_scolaire")},
            },
        ),
        migrations.CreateModel(
            name="AnalyseTravailMaternelle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comprend_demandes",
                    models.BooleanField(
                        default=False,
                        verbose_name="L'enfant comprend ce qu'on lui demande",
                    ),
                ),
                (
                    "ne_comprend_pas",
                    models.BooleanField(
                        default=False,
                        verbose_name="L'enfant ne comprend pas ce qu'on lui demande",
                    ),
                ),
                (
                    "trop_jeune",
                    models.BooleanField(
                        default=False,
                        verbose_name="L'enfant est trop jeune pour cette classe",
                    ),
                ),
                (
                    "fixe_attention",
                    models.BooleanField(
                        default=False, verbose_name="L'enfant fixe son attention"
                    ),
                ),
                (
                    "pas_probleme_monitrice",
                    models.BooleanField(
                        default=False,
                        verbose_name="L'enfant n'a pas de problème avec sa monitrice",
                    ),
                ),
                (
                    "pas_probleme_camarades",
                    models.BooleanField(
                        default=False,
                        verbose_name="L'enfant n'a pas de problème avec ses camarades",
                    ),
                ),
                (
                    "pas_probleme_famille",
                    models.BooleanField(
                        default=False,
                        verbose_name="L'enfant n'a pas de problème avec sa famille",
                    ),
                ),
                (
                    "est_doue",
                    models.BooleanField(
                        default=False, verbose_name="L'enfant est doué"
                    ),
                ),
                (
                    "est_paresseux",
                    models.BooleanField(
                        default=False, verbose_name="L'enfant est paresseux"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True, null=True, verbose_name="Commentaire supplémentaire"
                    ),
                ),
                (
                    "evaluation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyse_travail",
                        to="notes.evaluationmaternelle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analyse du travail (maternelle)",
                "verbose_name_plural": "Analyses du travail (maternelle)",
            },
        ),
        migrations.CreateModel(
            name="MatiereNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom de la matière"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Ex: MATH, FR, ANG",
                        max_length=20,
                        verbose_name="Code",
                    ),
                ),
                (
                    "coefficient",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=1.0,
                        max_digits=4,
                        null=True,
                        verbose_name="Coefficient",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Active")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matieres",
                        to="notes.classenote",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matieres_notes_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Matière (Notes)",
                "verbose_name_plural": "Matières (Notes)",
                "ordering": ["nom"],
                "unique_together": {("classe", "code")},
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        max_length=200, verbose_name="Titre de l'évaluation"
                    ),
                ),
                (
                    "type_evaluation",
                    models.CharField(
                        choices=[
                            ("DEVOIR", "Devoir"),
                            ("COMPOSITION", "Composition"),
                            ("EXAMEN", "Examen"),
                            ("CONTROLE", "Contrôle"),
                            ("INTERROGATION", "Interrogation"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "periode",
                    models.CharField(
                        choices=[
                            ("OCTOBRE", "Octobre"),
                            ("NOVEMBRE", "Novembre"),
                            ("DECEMBRE", "Décembre"),
                            ("JANVIER", "Janvier"),
                            ("FEVRIER", "Février"),
                            ("MARS", "Mars"),
                            ("AVRIL", "Avril"),
                            ("MAI", "Mai"),
                            ("JUIN", "Juin"),
                            ("TRIMESTRE_1", "Trimestre 1"),
                            ("TRIMESTRE_2", "Trimestre 2"),
                            ("TRIMESTRE_3", "Trimestre 3"),
                            ("SEMESTRE_1", "Semestre 1"),
                            ("SEMESTRE_2", "Semestre 2"),
                        ],
                        max_length=20,
                        verbose_name="Période",
                    ),
                ),
                (
                    "date_evaluation",
                    models.DateField(verbose_name="Date de l'évaluation"),
                ),
                (
                    "note_sur",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        max_digits=5,
                        verbose_name="Note sur",
                    ),
                ),
                (
                    "coefficient",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=4,
                        verbose_name="Coefficient",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="notes.matierenote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation",
                "verbose_name_plural": "Évaluations",
                "ordering": ["-date_evaluation"],
            },
        ),
        migrations.CreateModel(
            name="RecommandationMaternelle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "encourager_feliciter",
                    models.BooleanField(
                        default=False, verbose_name="Enfant à encourager et à féliciter"
                    ),
                ),
                (
                    "suivre_domicile",
                    models.BooleanField(
                        default=False, verbose_name="Enfant à suivre à domicile"
                    ),
                ),
                (
                    "gouter_dans_sac",
                    models.BooleanField(
                        default=False,
                        verbose_name="Mettre le goûter dans le sac de l'enfant",
                    ),
                ),
                (
                    "aide_encouragement_parents",
                    models.BooleanField(
                        default=False,
                        verbose_name="L'enfant a besoin d'aide et d'encouragement des parents",
                    ),
                ),
                (
                    "amour_parental",
                    models.BooleanField(
                        default=False,
                        verbose_name="L'enfant a besoin de l'amour maternel et paternel",
                    ),
                ),
                (
                    "besoin_epanouissement",
                    models.BooleanField(
                        default=False, verbose_name="L'enfant a besoin d'être épanoui"
                    ),
                ),
                (
                    "sorties_educatives",
                    models.BooleanField(
                        default=False,
                        verbose_name="L'enfant a besoin de sorties éducatives et récréatives",
                    ),
                ),
                (
                    "aide_intellectuelle",
                    models.BooleanField(
                        default=False,
                        verbose_name="L'enfant a besoin de l'aide de la monitrice et des parents pour développer ses facultés intellectuelles",
                    ),
                ),
                (
                    "douceur_patience",
                    models.BooleanField(
                        default=False,
                        verbose_name="L'enfant doit être pris avec beaucoup de douceur et de patience",
                    ),
                ),
                (
                    "besoin_fermete",
                    models.BooleanField(
                        default=False, verbose_name="L'enfant a besoin de fermeté"
                    ),
                ),
                (
                    "esprit_inferiorite",
                    models.BooleanField(
                        default=False, verbose_name="L'enfant a un esprit d'infériorité"
                    ),
                ),
                (
                    "attention_particuliere",
                    models.BooleanField(
                        default=False,
                        verbose_name="L'enfant a besoin d'une attention particulière des parents",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Recommandation personnalisée",
                    ),
                ),
                (
                    "evaluation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommandations",
                        to="notes.evaluationmaternelle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommandation (maternelle)",
                "verbose_name_plural": "Recommandations (maternelle)",
            },
        ),
        migrations.CreateModel(
            name="ThemeBulletin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom du thème")),
                (
                    "couleur_primaire",
                    models.CharField(
                        default="#2c3e50",
                        help_text="Ex: #2c3e50",
                        max_length=7,
                        verbose_name="Couleur primaire",
                    ),
                ),
                (
                    "couleur_secondaire",
                    models.CharField(
                        default="#3498db",
                        help_text="Ex: #3498db",
                        max_length=7,
                        verbose_name="Couleur secondaire",
                    ),
                ),
                (
                    "couleur_accent",
                    models.CharField(
                        default="#e74c3c",
                        help_text="Ex: #e74c3c",
                        max_length=7,
                        verbose_name="Couleur accent",
                    ),
                ),
                (
                    "couleur_texte_principal",
                    models.CharField(
                        default="#2c3e50", max_length=7, verbose_name="Texte principal"
                    ),
                ),
                (
                    "couleur_texte_secondaire",
                    models.CharField(
                        default="#7f8c8d", max_length=7, verbose_name="Texte secondaire"
                    ),
                ),
                (
                    "couleur_fond_header",
                    models.CharField(
                        default="#2c3e50", max_length=7, verbose_name="Fond en-tête"
                    ),
                ),
                (
                    "couleur_fond_tableau",
                    models.CharField(
                        default="#ecf0f1", max_length=7, verbose_name="Fond tableau"
                    ),
                ),
                (
                    "couleur_fond_carte",
                    models.CharField(
                        default="#ffffff", max_length=7, verbose_name="Fond cartes"
                    ),
                ),
                (
                    "couleur_bordure",
                    models.CharField(
                        default="#bdc3c7", max_length=7, verbose_name="Bordures"
                    ),
                ),
                (
                    "couleur_mention_tb",
                    models.CharField(
                        default="#27ae60",
                        max_length=7,
                        verbose_name="Mention Très Bien",
                    ),
                ),
                (
                    "couleur_mention_bien",
                    models.CharField(
                        default="#3498db", max_length=7, verbose_name="Mention Bien"
                    ),
                ),
                (
                    "couleur_mention_ab",
                    models.CharField(
                        default="#f39c12",
                        max_length=7,
                        verbose_name="Mention Assez Bien",
                    ),
                ),
                (
                    "couleur_mention_passable",
                    models.CharField(
                        default="#e67e22", max_length=7, verbose_name="Mention Passable"
                    ),
                ),
                (
                    "couleur_mention_insuffisant",
                    models.CharField(
                        default="#e74c3c",
                        max_length=7,
                        verbose_name="Mention Insuffisant",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(default=False, verbose_name="Thème actif"),
                ),
                (
                    "par_defaut",
                    models.BooleanField(default=False, verbose_name="Thème par défaut"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ecole",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="themes_bulletin",
                        to="eleves.ecole",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thème de bulletin",
                "verbose_name_plural": "Thèmes de bulletin",
                "ordering": ["-par_defaut", "-actif", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Classement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periode", models.CharField(max_length=50, verbose_name="Période")),
                (
                    "annee_scolaire",
                    models.CharField(max_length=9, verbose_name="Année scolaire"),
                ),
                (
                    "moyenne_generale",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Moyenne générale"
                    ),
                ),
                (
                    "total_points",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Total points"
                    ),
                ),
                (
                    "total_coefficients",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Total coefficients",
                    ),
                ),
                ("rang", models.PositiveIntegerField(verbose_name="Rang")),
                (
                    "rang_formate",
                    models.CharField(max_length=20, verbose_name="Rang formaté"),
                ),
                (
                    "effectif",
                    models.PositiveIntegerField(verbose_name="Effectif de la classe"),
                ),
                (
                    "mention",
                    models.CharField(blank=True, max_length=50, verbose_name="Mention"),
                ),
                (
                    "appreciation",
                    models.TextField(blank=True, verbose_name="Appréciation"),
                ),
                (
                    "date_calcul",
                    models.DateTimeField(auto_now=True, verbose_name="Date du calcul"),
                ),
                (
                    "calcule_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classements",
                        to="eleves.eleve",
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classements",
                        to="notes.classenote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classement",
                "verbose_name_plural": "Classements",
                "ordering": ["classe", "periode", "rang"],
                "indexes": [
                    models.Index(
                        fields=["classe", "periode", "annee_scolaire"],
                        name="notes_class_classe__52dfff_idx",
                    ),
                    models.Index(
                        fields=["eleve", "periode"],
                        name="notes_class_eleve_i_4bea5e_idx",
                    ),
                ],
                "unique_together": {("eleve", "classe", "periode", "annee_scolaire")},
            },
        ),
        migrations.CreateModel(
            name="BulletinMaternelle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trimestre",
                    models.CharField(
                        choices=[
                            ("TRIMESTRE_1", "Trimestre 1"),
                            ("TRIMESTRE_2", "Trimestre 2"),
                            ("TRIMESTRE_3", "Trimestre 3"),
                        ],
                        max_length=20,
                        verbose_name="Trimestre",
                    ),
                ),
                (
                    "annee_scolaire",
                    models.CharField(max_length=9, verbose_name="Année scolaire"),
                ),
                (
                    "analyses",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Analyses du travail"
                    ),
                ),
                (
                    "recommandations",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Recommandations"
                    ),
                ),
                (
                    "appreciation_generale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Appréciation générale"
                    ),
                ),
                (
                    "signature_monitrice",
                    models.BooleanField(
                        default=False, verbose_name="Signé par la monitrice"
                    ),
                ),
                (
                    "signature_directeur",
                    models.BooleanField(
                        default=False, verbose_name="Signé par le directeur"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulletins_maternelle",
                        to="eleves.eleve",
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulletins_maternelle",
                        to="notes.classenote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulletin maternelle",
                "verbose_name_plural": "Bulletins maternelle",
                "ordering": ["eleve", "trimestre"],
                "unique_together": {("eleve", "trimestre", "annee_scolaire")},
            },
        ),
        migrations.CreateModel(
            name="CompositionNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periode",
                    models.CharField(
                        choices=[
                            ("SEMESTRE_1", "Semestre 1"),
                            ("SEMESTRE_2", "Semestre 2"),
                            ("TRIMESTRE_1", "Trimestre 1"),
                            ("TRIMESTRE_2", "Trimestre 2"),
                            ("TRIMESTRE_3", "Trimestre 3"),
                        ],
                        max_length=20,
                        verbose_name="Période",
                    ),
                ),
                (
                    "annee_scolaire",
                    models.CharField(max_length=9, verbose_name="Année scolaire"),
                ),
                (
                    "note",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Note sur 20"
                    ),
                ),
                ("absent", models.BooleanField(default=False, verbose_name="Absent")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compositions",
                        to="eleves.eleve",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compositions",
                        to="notes.matierenote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note de composition",
                "verbose_name_plural": "Notes de composition",
                "ordering": ["eleve", "matiere", "periode"],
                "indexes": [
                    models.Index(
                        fields=["annee_scolaire", "periode"],
                        name="notes_compo_annee_s_3a0c82_idx",
                    ),
                    models.Index(
                        fields=["eleve", "annee_scolaire"],
                        name="notes_compo_eleve_i_692c3d_idx",
                    ),
                    models.Index(
                        fields=["matiere", "annee_scolaire"],
                        name="notes_compo_matiere_d81fea_idx",
                    ),
                ],
                "unique_together": {("eleve", "matiere", "periode", "annee_scolaire")},
            },
        ),
        migrations.CreateModel(
            name="AppreciationMaternelle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trimestre",
                    models.CharField(
                        choices=[
                            ("TRIMESTRE_1", "Trimestre 1"),
                            ("TRIMESTRE_2", "Trimestre 2"),
                            ("TRIMESTRE_3", "Trimestre 3"),
                        ],
                        max_length=20,
                        verbose_name="Trimestre",
                    ),
                ),
                (
                    "annee_scolaire",
                    models.CharField(max_length=9, verbose_name="Année scolaire"),
                ),
                (
                    "appreciation",
                    models.CharField(
                        choices=[
                            ("A+", "Excellent"),
                            ("A", "Très bien"),
                            ("B+", "Bien"),
                            ("B", "Assez bien"),
                            ("B-", "Moyen"),
                            ("C", "Passable"),
                            ("D", "Éprouve des difficultés"),
                        ],
                        max_length=20,
                        verbose_name="Appréciation",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, null=True, verbose_name="Commentaire"),
                ),
                ("absent", models.BooleanField(default=False, verbose_name="Absent")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appreciations_maternelle",
                        to="eleves.eleve",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appreciations_maternelle",
                        to="notes.matierenote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appréciation maternelle",
                "verbose_name_plural": "Appréciations maternelle",
                "ordering": ["eleve", "matiere", "trimestre"],
                "unique_together": {
                    ("eleve", "matiere", "trimestre", "annee_scolaire")
                },
            },
        ),
        migrations.CreateModel(
            name="NoteEleve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Note obtenue",
                    ),
                ),
                ("absent", models.BooleanField(default=False, verbose_name="Absent")),
                (
                    "commentaire",
                    models.TextField(blank=True, null=True, verbose_name="Commentaire"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes_saisies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_evaluations",
                        to="eleves.eleve",
                    ),
                ),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="notes.evaluation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note élève",
                "verbose_name_plural": "Notes élèves",
                "ordering": ["eleve__nom", "eleve__prenom"],
                "unique_together": {("evaluation", "eleve")},
            },
        ),
        migrations.CreateModel(
            name="NoteMaternelle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Note sur 10",
                    ),
                ),
                (
                    "lettre",
                    models.CharField(blank=True, max_length=2, verbose_name="Lettre"),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, null=True, verbose_name="Commentaire"),
                ),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_matieres",
                        to="notes.evaluationmaternelle",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_maternelle",
                        to="notes.matierenote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note maternelle",
                "verbose_name_plural": "Notes maternelle",
                "unique_together": {("evaluation", "matiere")},
            },
        ),
        migrations.CreateModel(
            name="NoteMensuelle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mois",
                    models.CharField(
                        choices=[
                            ("OCTOBRE", "Octobre"),
                            ("NOVEMBRE", "Novembre"),
                            ("DECEMBRE", "Décembre"),
                            ("JANVIER", "Janvier"),
                            ("FEVRIER", "Février"),
                            ("MARS", "Mars"),
                            ("AVRIL", "Avril"),
                            ("MAI", "Mai"),
                            ("JUIN", "Juin"),
                        ],
                        max_length=20,
                        verbose_name="Mois",
                    ),
                ),
                (
                    "annee_scolaire",
                    models.CharField(max_length=9, verbose_name="Année scolaire"),
                ),
                (
                    "note",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Note sur 20",
                    ),
                ),
                ("absent", models.BooleanField(default=False, verbose_name="Absent")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_mensuelles",
                        to="eleves.eleve",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_mensuelles",
                        to="notes.matierenote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note mensuelle",
                "verbose_name_plural": "Notes mensuelles",
                "ordering": ["eleve", "matiere", "mois"],
                "indexes": [
                    models.Index(
                        fields=["annee_scolaire", "mois"],
                        name="notes_notem_annee_s_179f8a_idx",
                    ),
                    models.Index(
                        fields=["eleve", "annee_scolaire"],
                        name="notes_notem_eleve_i_9d3c09_idx",
                    ),
                    models.Index(
                        fields=["matiere", "annee_scolaire"],
                        name="notes_notem_matiere_cce9c2_idx",
                    ),
                ],
                "unique_together": {("eleve", "matiere", "mois", "annee_scolaire")},
            },
        ),
    ]
