# Generated by Django 5.1.3 on 2026-02-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compositionnote",
            name="note",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Note sur 20",
            ),
        ),
    ]
