# Generated by Django 5.2.6 on 2026-03-10 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0012_ecole_censeur'),
        ('notes', '0002_alter_compositionnote_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appreciationmaternelle',
            index=models.Index(fields=['eleve', 'trimestre', 'annee_scolaire'], name='appmat_eleve_trim_idx'),
        ),
        migrations.AddIndex(
            model_name='appreciationmaternelle',
            index=models.Index(fields=['matiere', 'trimestre', 'annee_scolaire'], name='appmat_mat_trim_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['matiere', 'periode'], name='eval_matiere_periode_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['matiere', 'type_evaluation'], name='eval_matiere_type_idx'),
        ),
        migrations.AddIndex(
            model_name='noteeleve',
            index=models.Index(fields=['eleve'], name='note_eleve_idx'),
        ),
        migrations.AddIndex(
            model_name='noteeleve',
            index=models.Index(fields=['evaluation', 'eleve'], name='note_eval_eleve_idx'),
        ),
    ]
