# Generated by Django 5.2.1 on 2026-04-09 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0013_add_image_ecole'),
        ('notes', '0003_add_perf_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="Date de l'activité")),
                ('type_activite', models.CharField(choices=[('EVALUATION', 'Évaluation'), ('SPORTIVE', 'Sportive'), ('CULTURELLE', 'Culturelle'), ('ARTISTIQUE', 'Artistique'), ('SORTIE', 'Sortie éducative'), ('AUTRE', 'Autre')], max_length=20, verbose_name="Type d'activité")),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'activité")),
                ('description', models.TextField(blank=True, verbose_name='Description / Observation')),
                ('appreciation', models.CharField(blank=True, max_length=100, verbose_name='Appréciation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_journalieres', to='notes.classenote')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_journalieres', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Activité journalière',
                'verbose_name_plural': 'Activités journalières',
                'ordering': ['-date', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointeActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='activites_journalieres/%Y/%m/', verbose_name='Fichier')),
                ('legende', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='notes.activitejournaliere')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
        migrations.AddIndex(
            model_name='activitejournaliere',
            index=models.Index(fields=['classe', 'date'], name='notes_activ_classe__6bbf9e_idx'),
        ),
        migrations.AddIndex(
            model_name='activitejournaliere',
            index=models.Index(fields=['eleve', 'date'], name='notes_activ_eleve_i_040efb_idx'),
        ),
    ]
