# Generated by Django 5.2.6 on 2026-05-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_etendre_types_activite_vie_scolaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitejournaliere',
            options={'ordering': ['-date', '-date_creation'], 'verbose_name': 'Observation de vie scolaire', 'verbose_name_plural': 'Observations de vie scolaire'},
        ),
    ]
