# Generated by Django 5.2.6 on 2026-07-19 21:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0015_historiqueeleve_sync_tracking'),
        ('notes', '0008_complete_sync_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('mois', models.CharField(choices=[('OCTOBRE', 'Octobre'), ('NOVEMBRE', 'Novembre'), ('DECEMBRE', 'Décembre'), ('JANVIER', 'Janvier'), ('FEVRIER', 'Février'), ('MARS', 'Mars'), ('AVRIL', 'Avril'), ('MAI', 'Mai'), ('JUIN', 'Juin')], max_length=20, verbose_name='Mois')),
                ('annee_scolaire', models.CharField(max_length=9, verbose_name='Année scolaire')),
                ('type_note', models.CharField(choices=[('COURS', 'Note de cours / interrogation'), ('ORALE', 'Évaluation orale'), ('ECRITE', 'Évaluation écrite'), ('DEVOIR', 'Devoir maison'), ('PARTICIPATION', 'Participation en classe')], max_length=15, verbose_name='Type de note')),
                ('note', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Note sur 20')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('observation', models.CharField(blank=True, max_length=200, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_suivi_creees', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_suivi', to='eleves.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_suivi', to='notes.matierenote')),
            ],
            options={
                'verbose_name': 'Note de suivi',
                'verbose_name_plural': 'Notes de suivi',
                'ordering': ['-date', 'eleve__prenom', 'eleve__nom'],
                'indexes': [models.Index(fields=['matiere', 'mois', 'annee_scolaire'], name='notes_notes_matiere_f63f96_idx'), models.Index(fields=['eleve', 'matiere', 'mois'], name='notes_notes_eleve_i_36c8e9_idx'), models.Index(fields=['type_note'], name='notes_notes_type_no_bc8656_idx')],
            },
        ),
    ]
