# Generated by Django 5.2.6 on 2026-07-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_notesuivi'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesuivi',
            name='numero',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='N° (ex: interrogation 1, 2, 3)'),
        ),
    ]
