# Generated by Django 5.2.6 on 2026-07-20 04:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0015_historiqueeleve_sync_tracking'),
        ('notes', '0010_notesuivi_numero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du devoir')),
                ('description', models.TextField(blank=True, verbose_name='Consigne / description')),
                ('date_donne', models.DateField(verbose_name='Date où le devoir est donné')),
                ('date_remise', models.DateField(verbose_name='Date de remise (échéance)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs', to='notes.classenote')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoirs_crees', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs', to='notes.matierenote')),
            ],
            options={
                'verbose_name': 'Devoir',
                'verbose_name_plural': 'Devoirs',
                'ordering': ['-date_remise', '-date_donne'],
            },
        ),
        migrations.CreateModel(
            name='RemiseDevoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('statut', models.CharField(choices=[('NON_RENDU', 'Non rendu'), ('RENDU', 'Rendu'), ('EN_RETARD', 'Rendu en retard'), ('EXCUSE', 'Excusé')], default='NON_RENDU', max_length=12)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note du devoir (optionnel)')),
                ('observation', models.CharField(blank=True, max_length=200)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remises', to='notes.devoir')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remises_devoirs', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Remise de devoir',
                'verbose_name_plural': 'Remises de devoirs',
            },
        ),
        migrations.AddIndex(
            model_name='devoir',
            index=models.Index(fields=['classe', 'date_remise'], name='notes_devoi_classe__636868_idx'),
        ),
        migrations.AddIndex(
            model_name='devoir',
            index=models.Index(fields=['matiere'], name='notes_devoi_matiere_08b2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='remisedevoir',
            index=models.Index(fields=['devoir', 'statut'], name='notes_remis_devoir__80c9e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='remisedevoir',
            constraint=models.UniqueConstraint(fields=('devoir', 'eleve'), name='unique_remise_devoir_eleve'),
        ),
    ]
