# Generated by Django 5.2.6 on 2026-07-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_devoir_remisedevoir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoir',
            name='compte_bonus',
            field=models.BooleanField(default=False, help_text='Si activé, les notes saisies pour ce devoir alimentent le bonus de suivi du mois de la date de remise.', verbose_name='Compter les notes de ce devoir dans le bonus mensuel'),
        ),
    ]
