# Generated by Django 5.2.7 on 2025-10-31 17:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0009_alter_eleve_date_naissance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'itinéraire")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('quartiers', models.TextField(help_text='Liste des quartiers desservis (un par ligne)', verbose_name='Quartiers desservis')),
                ('heure_depart_matin', models.TimeField(verbose_name='Heure départ matin')),
                ('heure_retour_soir', models.TimeField(verbose_name='Heure retour soir')),
                ('capacite', models.IntegerField(default=40, verbose_name='Capacité')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Itinéraire',
                'verbose_name_plural': 'Itinéraires',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('BUS', 'Transport Scolaire'), ('CANTINE', 'Cantine'), ('GARDERIE', 'Garderie'), ('ETUDE', 'Étude Surveillée')], max_length=50, unique=True, verbose_name='Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('tarif_mensuel', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='Tarif mensuel (GNF)')),
                ('tarif_trimestriel', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='Tarif trimestriel (GNF)')),
                ('tarif_annuel', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='Tarif annuel (GNF)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Type d'abonnement",
                'verbose_name_plural': "Types d'abonnements",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='AbonnementCantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel')], max_length=20, verbose_name='Durée')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant (GNF)')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('EXPIRE', 'Expiré'), ('RESILIE', 'Résilié')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('regime_alimentaire', models.CharField(choices=[('NORMAL', 'Normal'), ('VEGETARIEN', 'Végétarien'), ('SANS_PORC', 'Sans porc'), ('SANS_GLUTEN', 'Sans gluten'), ('ALLERGIE', 'Régime spécial (allergie)')], default='NORMAL', max_length=20, verbose_name='Régime alimentaire')),
                ('allergies', models.TextField(blank=True, help_text='Précisez les allergies ou intolérances', null=True, verbose_name='Allergies alimentaires')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonnements_cantine_crees', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.eleve', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Abonnement cantine',
                'verbose_name_plural': 'Abonnements cantine',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='AbonnementBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel')], max_length=20, verbose_name='Durée')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant (GNF)')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('EXPIRE', 'Expiré'), ('RESILIE', 'Résilié')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('point_montee', models.CharField(max_length=200, verbose_name='Point de montée')),
                ('point_descente', models.CharField(max_length=200, verbose_name='Point de descente')),
                ('contact_urgence', models.CharField(max_length=20, verbose_name="Contact d'urgence")),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonnements_bus_crees', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.eleve', verbose_name='Élève')),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abonnements.itineraire', verbose_name='Itinéraire')),
            ],
            options={
                'verbose_name': 'Abonnement bus',
                'verbose_name_plural': 'Abonnements bus',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MenuCantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi')], max_length=20, verbose_name='Jour')),
                ('semaine', models.IntegerField(verbose_name='Numéro de semaine')),
                ('entree', models.CharField(max_length=200, verbose_name='Entrée')),
                ('plat_principal', models.CharField(max_length=200, verbose_name='Plat principal')),
                ('accompagnement', models.CharField(max_length=200, verbose_name='Accompagnement')),
                ('dessert', models.CharField(max_length=200, verbose_name='Dessert')),
                ('boisson', models.CharField(default='Eau', max_length=100, verbose_name='Boisson')),
                ('date_menu', models.DateField(verbose_name='Date du menu')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Menu cantine',
                'verbose_name_plural': 'Menus cantine',
                'ordering': ['-date_menu', 'jour'],
                'unique_together': {('jour', 'semaine', 'date_menu')},
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel')], max_length=20, verbose_name='Durée')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant (GNF)')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('EXPIRE', 'Expiré'), ('RESILIE', 'Résilié')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonnements_crees', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.eleve', verbose_name='Élève')),
                ('type_abonnement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abonnements.typeabonnement', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PresenceCantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('present', models.BooleanField(default=True, verbose_name='Présent')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonnements.abonnementcantine', verbose_name='Abonnement')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonnements.menucantine', verbose_name='Menu')),
            ],
            options={
                'verbose_name': 'Présence cantine',
                'verbose_name_plural': 'Présences cantine',
                'ordering': ['-date'],
                'unique_together': {('abonnement', 'date')},
            },
        ),
    ]
