# Generated by Django 5.2.6 on 2026-07-19 19:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0015_historiqueeleve_sync_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('date', models.DateField(db_index=True, verbose_name='Date du pointage')),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('RETARD', 'En retard'), ('JUSTIFIE', 'Absence justifiée')], default='PRESENT', max_length=10)),
                ('motif', models.CharField(blank=True, max_length=200, verbose_name='Motif / observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='eleves.classe')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages_crees', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Présence journalière',
                'verbose_name_plural': 'Présences journalières',
                'ordering': ['-date', 'eleve__nom', 'eleve__prenom'],
                'indexes': [models.Index(fields=['classe', 'date'], name='presence_pr_classe__07a7e0_idx'), models.Index(fields=['date', 'statut'], name='presence_pr_date_756371_idx'), models.Index(fields=['eleve', 'date'], name='presence_pr_eleve_i_ca9b56_idx')],
                'constraints': [models.UniqueConstraint(fields=('eleve', 'date'), name='unique_presence_eleve_date')],
            },
        ),
    ]
