# Generated by Django 5.2.6 on 2026-07-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncchange',
            name='tentatives',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
