# Generated by Django 5.2.6 on 2026-07-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0016_ecole_bonus_suivi_actif'),
        ('synchronisation', '0002_syncchange_tentatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncchange',
            name='client_change_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='syncchange',
            name='statut',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPLIED', 'Applique'), ('FAILED', 'Echec (sera rejoue)'), ('ABANDONED', 'Abandonne apres trop de tentatives')], db_index=True, default='PENDING', max_length=12),
        ),
        migrations.AddIndex(
            model_name='syncchange',
            index=models.Index(fields=['device', 'client_change_id'], name='synchronisa_device__2f50ee_idx'),
        ),
    ]
