# Generated by Django 5.2.6 on 2025-10-10 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0002_enseignant_heures_mensuelles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('RETARD', 'Retard'), ('CONGE', 'Congé'), ('MALADIE', 'Maladie'), ('PERMISSION', 'Permission')], default='PRESENT', max_length=20, verbose_name='Statut')),
                ('heure_arrivee', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('heure_depart', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('heures_travaillees', models.DecimalField(blank=True, decimal_places=2, help_text='Calculé automatiquement ou saisi manuellement', max_digits=4, null=True, verbose_name='Heures travaillées')),
                ('observations', models.TextField(blank=True, help_text="Motif d'absence, retard, etc.", verbose_name='Observations')),
                ('justifie', models.BooleanField(default=False, help_text='Absence ou retard justifié', verbose_name='Justifié')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='salaires.enseignant', verbose_name='Enseignant')),
                ('pointe_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Pointé par')),
            ],
            options={
                'verbose_name': 'Présence enseignant',
                'verbose_name_plural': 'Présences enseignants',
                'ordering': ['-date', 'enseignant__nom'],
                'indexes': [models.Index(fields=['enseignant', 'date'], name='salaires_pr_enseign_d7143c_idx'), models.Index(fields=['date', 'statut'], name='salaires_pr_date_bc00b9_idx')],
                'unique_together': {('enseignant', 'date')},
            },
        ),
    ]
