# Generated by Django 5.2.6 on 2026-08-09 07:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def renseigner_taux_historique(apps, schema_editor):
    EtatSalaire = apps.get_model('salaires', 'EtatSalaire')
    DetailHeuresClasse = apps.get_model('salaires', 'DetailHeuresClasse')
    etats = list(
        EtatSalaire.objects.filter(
            enseignant__type_enseignant='SECONDAIRE',
            taux_horaire_applique__isnull=True,
        ).select_related('enseignant')
    )

    for etat in etats:
        detail = DetailHeuresClasse.objects.filter(
            etat_salaire_id=etat.id
        ).order_by('id').first()
        etat.taux_horaire_applique = (
            detail.taux_horaire_applique
            if detail is not None
            else etat.enseignant.taux_horaire
        )

    if etats:
        EtatSalaire.objects.bulk_update(etats, ['taux_horaire_applique'])


def effacer_taux_historique(apps, schema_editor):
    EtatSalaire = apps.get_model('salaires', 'EtatSalaire')
    EtatSalaire.objects.update(taux_horaire_applique=None)


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0004_add_sync_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatsalaire',
            name='taux_horaire_applique',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Taux conservé au moment du calcul pour l'historique", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Taux horaire appliqué'),
        ),
        migrations.RunPython(renseigner_taux_historique, effacer_taux_historique),
        migrations.AlterField(
            model_name='affectationclasse',
            name='heures_par_semaine',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Nombre d'heures d'enseignement par semaine dans cette classe", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('168'))], verbose_name='Heures par semaine'),
        ),
        migrations.AlterField(
            model_name='detailheuresclasse',
            name='heures_prevues',
            field=models.DecimalField(decimal_places=2, help_text="Heures prévues selon l'affectation", max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Heures prévues'),
        ),
        migrations.AlterField(
            model_name='detailheuresclasse',
            name='heures_realisees',
            field=models.DecimalField(decimal_places=2, help_text='Heures effectivement enseignées', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Heures réalisées'),
        ),
        migrations.AlterField(
            model_name='detailheuresclasse',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='detailheuresclasse',
            name='taux_horaire_applique',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Taux horaire appliqué'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='heures_mensuelles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Nombre d'heures de travail prévues par mois (pour calcul précis du salaire)", max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('200'))], verbose_name='Heures mensuelles'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='salaire_fixe',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pour garderie, maternelle, primaire et administrateurs', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Salaire fixe (GNF)'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='taux_horaire',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pour les enseignants du secondaire uniquement', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Taux horaire (GNF)'),
        ),
        migrations.AlterField(
            model_name='etatsalaire',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Déductions'),
        ),
        migrations.AlterField(
            model_name='etatsalaire',
            name='primes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Primes'),
        ),
        migrations.AlterField(
            model_name='etatsalaire',
            name='salaire_base',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Salaire de base'),
        ),
        migrations.AlterField(
            model_name='etatsalaire',
            name='salaire_net',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Salaire net'),
        ),
        migrations.AlterField(
            model_name='periodesalaire',
            name='nombre_semaines',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.33'), help_text='Nombre moyen de semaines dans le mois (défaut: 4.33)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('6'))], verbose_name='Nombre de semaines'),
        ),
        migrations.AlterField(
            model_name='presenceenseignant',
            name='heures_travaillees',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculé automatiquement ou saisi manuellement', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Heures travaillées'),
        ),
    ]
