# Generated by Django 5.2.6 on 2026-08-30 21:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0006_saisie_heures_mensuelles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etatsalaire',
            name='avances',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total des avances rattachées à cette période et déduites du salaire net', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Avances sur salaire'),
        ),
        migrations.CreateModel(
            name='AvanceSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('date_avance', models.DateField(default=django.utils.timezone.localdate, verbose_name="Date de l'avance")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="Montant de l'avance (GNF)")),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence / reçu')),
                ('motif', models.TextField(blank=True, verbose_name='Motif / observations')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'À déduire'), ('DEDUITE', 'Déduite du salaire'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=16, verbose_name='Statut')),
                ('motif_annulation', models.TextField(blank=True, verbose_name="Motif de l'annulation")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_annulation', models.DateTimeField(blank=True, null=True)),
                ('annulee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances_salaire_annulees', to=settings.AUTH_USER_MODEL, verbose_name='Annulée par')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances_salaire_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_salaire', to='salaires.enseignant', verbose_name='Enseignant')),
                ('etat_salaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances_deduites', to='salaires.etatsalaire', verbose_name='État de salaire')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_salaire', to='salaires.periodesalaire', verbose_name='Période de déduction')),
            ],
            options={
                'verbose_name': 'Avance sur salaire',
                'verbose_name_plural': 'Avances sur salaire',
                'ordering': ['-date_avance', '-date_creation'],
                'indexes': [models.Index(fields=['enseignant', 'periode', 'statut'], name='sal_av_ens_per_stat_idx')],
            },
        ),
    ]
