# Generated by Django 5.2.6 on 2026-09-02 07:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0007_etatsalaire_avances_avancesalaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatsalaire',
            name='nombre_jours_presence',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de jours pointés présent ou en retard pendant la période', verbose_name='Nombre de jours de présence'),
        ),
        migrations.AlterField(
            model_name='etatsalaire',
            name='total_heures',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total des heures enseignées dans le mois', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Total heures'),
        ),
    ]
