# Generated by Django 5.2.6 on 2026-09-05 20:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0009_remplir_jours_presence_etats_existants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='salaire_fixe',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant mensuel négocié pour le personnel à salaire fixe, hors primes', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Salaire fixe (GNF)'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='type_enseignant',
            field=models.CharField(choices=[('GARDERIE', 'Garderie'), ('MATERNELLE', 'Maternelle'), ('PRIMAIRE', 'Primaire'), ('SECONDAIRE', 'Secondaire (taux horaire)'), ('ADMINISTRATEUR', 'Cadre / Administrateur'), ('CHAUFFEUR', 'Chauffeur'), ('VIGILE', 'Vigiles'), ('ENTRETIEN', 'Service entretien'), ('NOUNOU', 'Nounou'), ('RESTAURATION', 'Restauration')], max_length=20, verbose_name="Type d'enseignant"),
        ),
    ]
