# Generated by Django 5.2.6 on 2026-09-24 22:02

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def reprendre_primes_existantes(apps, schema_editor):
    """Les primes globales déjà saisies deviennent des primes exceptionnelles."""
    EtatSalaire = apps.get_model('salaires', 'EtatSalaire')
    EtatSalaire.objects.filter(primes__gt=0).update(
        prime_exceptionnelle=models.F('primes')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0022_attente_premier_paiement'),
        ('salaires', '0010_categories_personnel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Sert au calcul de la prime d'éloignement", max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Distance domicile-école (km)'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='fonction',
            field=models.CharField(blank=True, help_text='Ex. Directrice, Chargé de cours (CP1), Anglais', max_length=100, verbose_name='Charge ou fonction'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='heures_jeudi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Heures le jeudi'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='heures_lundi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Heures le lundi'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='heures_mardi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Heures le mardi'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='heures_mercredi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Heures le mercredi'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='heures_samedi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Heures le samedi'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='heures_vendredi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Heures le vendredi'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matricule',
            field=models.CharField(blank=True, max_length=30, verbose_name='Matricule'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='prime_craie',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant mensuel fixe', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de craie / révision (GNF)'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='prime_fonction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant mensuel fixe', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de fonction (GNF)'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='classes_professeur_principal',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='Classes tenues comme professeur principal'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='heures_a_prester',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Heures prévues par l'emploi du temps hebdomadaire sur le mois", max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Heures à prester'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='heures_absence',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Retirées des heures à prester de l'emploi du temps", max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Heures d'absence"),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='heures_revision',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Heures de révision'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='jours_chomes',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(31)], verbose_name='Jours chômés'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_anciennete',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prime d'ancienneté"),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_craie',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de craie / révision'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_eloignement',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prime d'éloignement"),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_exceptionnelle',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime exceptionnelle'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_fonction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de fonction'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_performance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de performance'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_professeur_principal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de professeur principal'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_revision',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prime d'heures de révision"),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='retenue_jours_chomes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Jours chômés multipliés par la retenue journalière du barème', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Retenue pour jours chômés'),
        ),
        migrations.AlterField(
            model_name='etatsalaire',
            name='primes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total recalculé à partir des primes détaillées', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Primes'),
        ),
        migrations.AlterField(
            model_name='etatsalaire',
            name='source_heures',
            field=models.CharField(blank=True, choices=[('', 'Non applicable'), ('POINTAGE', 'Pointages arrivée / départ'), ('SAISIE_MENSUELLE', 'Saisie mensuelle globale'), ('SALAIRE_FIXE', 'Salaire fixe négocié'), ('EMPLOI_DU_TEMPS', 'Emploi du temps hebdomadaire')], default='', help_text='Origine des heures ou du montant utilisé pour calculer le salaire', max_length=24, verbose_name='Source du calcul'),
        ),
        migrations.CreateModel(
            name='ParametresPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('prime_anciennete_par_an', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Multipliée par le nombre d'années depuis l'embauche", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prime d'ancienneté par année (GNF)")),
                ('prime_eloignement_par_km', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Multipliée par la distance domicile-école de la fiche du personnel', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prime d'éloignement par km (GNF)")),
                ('retenue_par_jour_chome', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Déduite du salaire pour chaque jour chômé saisi dans le mois', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Retenue par jour chômé (GNF)')),
                ('prime_professeur_principal', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Par classe tenue comme professeur principal (secondaire)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de professeur principal (GNF)')),
                ('prime_heure_revision', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Multipliée par les heures de révision du mois (secondaire)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime par heure de révision (GNF)')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ecole', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres_paie', to='eleves.ecole', verbose_name='École')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametres_paie_modifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètres de paie',
                'verbose_name_plural': 'Paramètres de paie',
            },
        ),
        migrations.RunPython(reprendre_primes_existantes, migrations.RunPython.noop),
    ]
