# Generated by Django 5.2.6 on 2026-09-25 05:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0011_modules_paie_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatsalaire',
            name='effectif_eleves',
            field=models.PositiveSmallIntegerField(default=0, help_text='Élèves de la classe tenue : sert à la prime de craie par élève', validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Effectif de la classe'),
        ),
        migrations.AddField(
            model_name='parametrespaie',
            name='prime_craie_par_eleve',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Multipliée par l'effectif de la classe tenue, saisi chaque mois", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de craie par élève (GNF)'),
        ),
    ]
