# Generated by Django 5.2.6 on 2025-10-14 06:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_alter_abonnementbus_date_expiration_and_more'),
        ('eleves', '0009_alter_eleve_date_naissance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnementCantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant (GNF)')),
                ('periodicite', models.CharField(choices=[('JOURNALIER', 'Journalier'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel')], default='MENSUEL', max_length=15)),
                ('type_repas', models.CharField(choices=[('DEJEUNER', 'Déjeuner uniquement'), ('GOUTER', 'Goûter uniquement'), ('COMPLET', 'Déjeuner + Goûter')], default='DEJEUNER', max_length=10)),
                ('date_debut', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de début')),
                ('date_expiration', models.DateField(db_index=True, verbose_name="Date d'expiration")),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('SUSPENDU', 'Suspendu')], db_index=True, default='ACTIF', max_length=10)),
                ('alerte_avant_jours', models.PositiveIntegerField(default=7, verbose_name='Alerte avant (jours)')),
                ('derniere_relance', models.DateTimeField(blank=True, null=True, verbose_name='Dernière relance')),
                ('regime_alimentaire', models.CharField(blank=True, help_text='Ex: Végétarien, Sans porc, Halal, etc.', max_length=100, verbose_name='Régime alimentaire')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergies alimentaires')),
                ('contact_parent', models.CharField(blank=True, max_length=100, verbose_name='Contact parent')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_cantine', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Abonnement cantine',
                'verbose_name_plural': 'Abonnements cantine',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['eleve', 'statut'], name='bus_abonnem_eleve_i_ad0c74_idx'), models.Index(fields=['eleve', 'date_expiration'], name='bus_abonnem_eleve_i_b21d74_idx'), models.Index(fields=['statut', 'date_expiration'], name='bus_abonnem_statut_096e9d_idx')],
            },
        ),
    ]
