# Generated by Django 5.2.6 on 2026-08-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_add_sync_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnementbus',
            name='reference_externe',
            field=models.CharField(blank=True, db_index=True, help_text='Numéro du reçu, transaction Mobile Money, chèque ou autre référence.', max_length=100, verbose_name='Référence externe du paiement'),
        ),
        migrations.AddField(
            model_name='abonnementcantine',
            name='reference_externe',
            field=models.CharField(blank=True, db_index=True, help_text='Numéro du reçu, transaction Mobile Money, chèque ou autre référence.', max_length=100, verbose_name='Référence externe du paiement'),
        ),
    ]
