# Generated by Django 5.2.6 on 2026-08-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_abonnementbus_reference_externe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnementbus',
            name='periodicite',
            field=models.CharField(choices=[('MENSUEL', 'Mensuel'), ('ANNUEL', 'Annuel'), ('T1', '1ère Tranche'), ('T2', '2ème Tranche'), ('T3', '3ème Tranche')], default='MENSUEL', help_text='Choisissez notamment Mensuel, Annuel ou une tranche.', max_length=10, verbose_name='Type de paiement'),
        ),
        migrations.AlterField(
            model_name='abonnementcantine',
            name='periodicite',
            field=models.CharField(choices=[('JOURNALIER', 'Journalier'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel')], default='MENSUEL', help_text='Le paiement annuel est disponible en plus des autres périodes.', max_length=15, verbose_name='Type de paiement'),
        ),
        migrations.AlterField(
            model_name='abonnementcantine',
            name='type_repas',
            field=models.CharField(choices=[('DEJEUNER', 'Déjeuner uniquement'), ('GOUTER', 'Goûter uniquement'), ('COMPLET', 'Déjeuner + Goûter'), ('REPAS_10H', 'Repas de 10 h'), ('REPAS_14H', 'Repas de 14 h')], default='DEJEUNER', help_text='Choisissez le repas et, si nécessaire, le service de 10 h ou de 14 h.', max_length=10, verbose_name='Type de repas / heure de service'),
        ),
    ]
